### ISSUE TITLE
Request to add Anki

### ISSUE THREAD

**Issue by Dos4dev** [yudina-m/english-resources#8]
Hey Maria, thank you for this is wonderful repository.
I want to introduce an exciting project.
Anki is a free and open-source flashcard program using spaced repetition, a technique from cognitive science for fast and long-lasting memorization

Official [web-page](https://apps.ankiweb.net/) 

This program helps me a lot. I hope it will be useful for others as well. 
@yudina-m what do you think about adding this app to the list?

**Comment by yudina-m** [comment]
done :)
